name: Sveglia Automatica App
on:
  schedule:
    - cron: '*/20 * * * *' # Gira ogni 20 minuti
  workflow_dispatch:      # Ti permette di avviarlo a mano

jobs:
  ping_job:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Streamlit
        run: |
          wget --spider --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "https://amazon-swag-dk5vxwh336x2kndkom4vqe.streamlit.app/"
